Feature workflow (#8)
* Feature workflow

* Feature workflow

* Feature workflow

* Fix env

* Fix path issue?

* fix image tag

* echo image tag

* empty

* release

diff --git a/.github/workflows/build-container-image.yml b/.github/workflows/build-container-image.yml
--- a/.github/workflows/build-container-image.yml
+++ b/.github/workflows/build-container-image.yml
@@ -15,6 +15,15 @@ on:
       repositoryName:
         required: true
         type: string
+      promtoolImageName:
+        required: true
+        type: string
+      promtoolVersion:
+        required: true
+        type: string
+      user:
+        required: true
+        type: string
 
 jobs:
   container-image-build:
@@ -89,3 +98,28 @@ jobs:
       - name: Check on failures
         if: steps.snyk-dockerfile.outcome != 'success'
         run: exit 1
+
+
+  code-test:
+    needs: container-image-build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3.1.0
+      - name: Download artifact
+        uses: actions/download-artifact@v3.0.1
+        with:
+          name: ${{ inputs.repositoryName }}
+          path: /tmp
+      - name: Load Docker image
+        run: |
+          docker load --input /tmp/${{ inputs.repositoryName }}.tar
+          echo "IMAGE_TAG=$(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep sre-monitoring-as-code)" >> $GITHUB_ENV
+      - name: echo image tag
+        run: echo "${{ env.IMAGE_TAG }}"
+      - name: Run monitoring mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ env.IMAGE_TAG }} -m monitoring -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+      - name: Run testing mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ env.IMAGE_TAG }} -m testing -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+      - name: Run promtool checks
+        run: for FILE in ${{ github.workspace }}/monitoring-as-code/output/prometheus-rules/*-rules.yaml; do docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data ${{ inputs.imageRegistry }}/${{ inputs.user }}/${{inputs.promtoolImageName}}:${{inputs.promtoolVersion}} check rules ${{ github.workspace }}/data/output/prometheus-rules/$(basename $FILE); if [ $? -ne 0 ]; then echo "Validation of rules files failed for $(basename $FILE) - exiting"; exit 1; fi done
