feat: run automation test by run mixin and validate the rules file vi… (#192)
* feat: run automation test by run mixin and validate the rules file via promtool

* refactor: add testing mixin

* refactor: added sre-promtool image reference to the promtool check step

* refactor: add sre-promtool docker image reference to the promtool check step

diff --git a/.github/workflows/docker-build-branch.yml b/.github/workflows/docker-build-branch.yml
--- a/.github/workflows/docker-build-branch.yml
+++ b/.github/workflows/docker-build-branch.yml
@@ -7,6 +7,9 @@ on:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
+  PROMTOOL_IMAGE_NAME: sre-promtool
+  PROMTOOL_VERSION: 2.38.0
+  USER: ho-cto
 
 jobs:
   publish:
@@ -49,6 +52,15 @@ jobs:
           build-args: |
             PACKAGE_TOKEN=${{secrets.GITHUB_TOKEN}}
             MAC_VERSION='#${{ github.event.number }}'
+
+      - name: Run monitoring mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ steps.meta.outputs.tags }} -m monitoring -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+
+      - name: Run testing mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ steps.meta.outputs.tags }} -m testing -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+
+      - name: Run promtool checks
+        run: for FILE in ${{ github.workspace }}/monitoring-as-code/output/prometheus-rules/*-rules.yaml; do docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data ${{env.REGISTRY}}/${{env.USER}}/${{env.PROMTOOL_IMAGE_NAME}}:${{env.PROMTOOL_VERSION}} check rules ${{ github.workspace }}/data/output/prometheus-rules/$(basename $FILE); if [ $? -ne 0 ]; then echo "Validation of rules files failed for $(basename $FILE) - exiting"; exit 1; fi done
 
       # Snyk security scan of Docker file only
       - name: Run Snyk to check Docker file for vulnerabilities
