feat: run automation test by run mixin and validate the rules file via promtool

diff --git a/.github/workflows/docker-build-branch.yml b/.github/workflows/docker-build-branch.yml
--- a/.github/workflows/docker-build-branch.yml
+++ b/.github/workflows/docker-build-branch.yml
@@ -50,6 +50,12 @@ jobs:
             PACKAGE_TOKEN=${{secrets.GITHUB_TOKEN}}
             MAC_VERSION='#${{ github.event.number }}'
 
+      - name: Run mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ steps.meta.outputs.tags }} -m monitoring -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+
+      - name: Run promtool checks
+        run: for FILE in ${{ github.workspace }}/monitoring-as-code/output/prometheus-rules/*-rules.yaml; do docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data dnanexus/promtool:2.9.2 check rules ${{ github.workspace }}/data/output/prometheus-rules/$(basename $FILE); if [ $? -ne 0 ]; then echo "Validation of rules files failed for $(basename $FILE) - exiting"; exit 1; fi done
+
       # Snyk security scan of Docker file only
       - name: Run Snyk to check Docker file for vulnerabilities
         id: snyk-dockerfile
